version: '3'

services:
  nginx:
    image: nginx:1.12
    command: ['/srv/hermod/docker/nginx/run_dev.sh']
    working_dir: /srv/hermod
    depends_on:
      - php-fpm
    volumes:
      - .:/srv/hermod:rw
      - ./docker/nginx/conf.d:/etc/nginx/conf.d:ro
    networks:
      - hermod
    environment:
      - DOMAIN_NAME=hermod.local

  php-fpm:
    image: hermod_php:dev
    volumes:
      - .:/srv/hermod:rw
    depends_on:
      - database
    env_file:
      - docker/config.env
    networks:
      - hermod

  database:
    image: postgres:9.6
    volumes:
      - ./docker/postgres/data:/var/lib/postgresql/data:rw
      - ./docker/postgres/add_uuid_extension.sh:/docker-entrypoint-initdb.d/add_uuid_extension.sh:ro
    env_file:
      - docker/config.env
    networks:
      - hermod

networks:
  hermod:
    driver: bridge
