# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:

    providers:
        token_user_provider:
            id: AppBundle\Security\TokenUserProvider

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        secured_area:
            pattern: ^/v1/
            stateless: true
            simple_preauth:
                authenticator: AppBundle\Security\TokenAuthenticator
            provider: token_user_provider

    role_hierarchy:
        ROLE_ROOT:
            - ROLE_V1_STATUS_PATCH_CREATE_EQUIPMENT_STATUS
            - ROLE_V1_LOCATION_PATCH_CREATE
            - ROLE_V1_LOCATION_PATCH_CREATE_FROM_REPORTER
            - ROLE_V1_ELEVATOR_IMPORT_CSV
