version: '3'

services:
  nginx:
    image: hermod_nginx:${VERSION}
    depends_on:
      - php-fpm
    networks:
      - network
      - traefik-net
    logging:
      driver: "syslog"
      options:
        syslog-facility: local6
        tag: hermod-nginx
    deploy:
      labels:
        - "traefik.frontend.rule=Host:${HOST}"
        - "traefik.docker.network=traefik-net"
        - "traefik.port=80"
        - "traefik.frontend.entryPoints=http"
      update_config:
        parallelism: 1
        delay: 10s
      replicas: 2

  php-fpm:
    image: hermod_php:${VERSION}
    env_file:
      - docker/config.env
    environment:
      LOG_PATH: "php://stderr"
    networks:
      - network
    logging:
      driver: "syslog"
      options:
        syslog-facility: local6
        tag: hermod-php-fpm
    deploy:
      labels:
        - "traefik.enable=false"
      update_config:
        parallelism: 1
        delay: 10s
      replicas: 2

networks:
  network:
    driver: overlay
  traefik-net:
    external: true
